remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - ./crypto/intro.md

title: CMP-5006 Cybersecurity
description: Fall 2023